### ISSUE TITLE
Feature idea: Custom animations

### ISSUE THREAD

**Issue by xhanl** [elonehoo/animated-unocss#59]
This is a small but beautiful preset, it works as expect and the demo is very convenient!

The only regret is that it would be great if this preset could support custom animations.

Is it possible to create a new feature that allow user configure custom animations by Preset Option using this [config](https://github.com/animated-unocss/animated-unocss/blob/main/src/animated.json) format?

**Comment by elonehoo** [comment]
🤔, let me try it
